arch: amd64
dist: trusty
language: go
go:
  - 1.15.x
before_install:
  - export GO111MODULE=on
install:
  - go get ./...
before_script:
  - |
    if [ -z "$TRAVIS_TAG" ]; then
      export TARGET_NAME=amber-login-dev
    else
      export TARGET_NAME=amber-login-$TRAVIS_TAG
    fi
script:
  - go test -test.bench=.* -coverprofile=coverage.txt -covermode=atomic
  - echo "building "$TARGET_NAME" ..."
  - env GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o $TARGET_NAME.linux.386.bin
  - env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o $TARGET_NAME.linux.amd64.bin
  - env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o $TARGET_NAME.darwin.amd64.bin
  - env GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o $TARGET_NAME.windows.386.exe
  - env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o $TARGET_NAME.windows.amd64.exe
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - wget https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz
  - tar -xvJf upx-3.95-amd64_linux.tar.xz
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.linux.386.bin
  - tar -cvJf $TARGET_NAME.linux.386.tar.xz $TARGET_NAME.linux.386.bin
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.linux.amd64.bin
  - tar -cvJf $TARGET_NAME.linux.amd64.tar.xz $TARGET_NAME.linux.amd64.bin
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.darwin.amd64.bin
  - tar -cvJf $TARGET_NAME.darwin.amd64.tar.xz $TARGET_NAME.darwin.amd64.bin
  - travis_wait ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.windows.386.exe
  - tar -cvJf $TARGET_NAME.windows.386.tar.xz $TARGET_NAME.windows.386.exe
  - travis_wait ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.windows.amd64.exe
  - tar -cvJf $TARGET_NAME.windows.amd64.tar.xz $TARGET_NAME.windows.amd64.exe
deploy:
  provider: releases
  api_key:
    secure: RT7IXSJKI5bvcStq3YSpbZH6bKxmjKFRg8xgjvzAp6M6CVGhfFNQaJ5LMFRc214PwDHv5Rc0yG1yUAg7p1hU1KjvCYeeWyWUClmPgdP07D997w+dWowt/zDe8rpZHpc7wdSCgnSswGQH5iB+UuqKfrCipXCbH+hkghRK5pANe1Ke9m6b2tf1seWmPCj2Eb9p3zeE0I4+SyIj7br1aN6o//TKREh+WaK5BCPxMCNUFyaDMHCoR9L6tHjhsl9RXyKtL3s5mzQQvO/HRTwWVwQqLdE2pGt+Ed4EXLqwoROetMfE0ThZm+WzNETWyosPYuS9eInyzQtTqhPg+eD/XzgKilmbOneW74kUk5ja158zjs45EOKb6wqa8ST+55gxdO+jI/tfWoE5dwzvnqB1xZMeSJLYkbUpKT4JN4wj90qEeJh1zlP6yzqZfMko4gvWhuIVYfreVoQCXd6tdUra8v8ZUqWJzqEtkNLxtaust+ax3kTKO8ubQdMiymta2zJho8he2G8Ud1icU9t9QejSJv2NdpP36RWuP6zqpGLMqDFTb9J6rEQycgWQPHp5PMtWYYUtMEj9FHxuqUfGBvL2YeAEsWns9OW19zeGECmPgW5uzJE85xzfRIYtBAVJ9Ho1tO0xr7v5vTcCn4mGXdgFts51LVvNCHXVkpsLjqM1QnXy1TA=
  file_glob: true
  file: $TARGET_NAME.*.tar.xz
  skip_cleanup: true
  on:
    repo: CharLemAznable/amber-login
    tags: true
